---
  output: 
  pdf_document:
  keep_tex: true
fig_caption: true
latex_engine: pdflatex
header-includes:
  -  \usepackage{hyperref}  
title: ""
geometry: margin=2cm

---

```{r setup, include=FALSE}

## Needed to set CC=g++ so that could install reticulate
M <- file.path(Sys.getenv("HOME"), ".R", ifelse(.Platform$OS.type == "windows", "Makevars.win", "Makevars"))
file.edit(M)
#install.packages("reticulate")

library(reticulate)
library(dplyr)
library(ggplot2)
library(tidyr)

```

```{python lets-simulate}

import numpy

# 1-year steps
N=100
ages = range(1,N)

risks1a = numpy.array([0.01,0.005,0.004,0.0005])
risks2a = numpy.array([0.01,0.005,0.002,0.0005])
risks1b = numpy.array([0.0035,0.005,0.004,0.0005,000.6,0.003])
risks2b = numpy.array([0.0035,0.005,0.002,0.0005,000.6,0.003])

pop = numpy.array([5000000,5000000])
cases=numpy.zeros((N-1,3))

for age in ages:
  cases[age-1,0]=age
  if age < 40:
    cases[age-1,1]=pow(age,3)*numpy.prod(risks1a)*pop[0]
    cases[age-1,2]=pow(age,3)*numpy.prod(risks2a)*pop[1]
  else:
    cases[age-1,1]=pow(age,5)*numpy.prod(risks1b)*pop[0]
    cases[age-1,2]=pow(age,5)*numpy.prod(risks2b)*pop[1]
  pop[0]=pop[0]-cases[age-1,1]
  pop[1]=pop[1]-cases[age-1,2]


````

```{r pretty-plots}

sim <- data.frame(age=py$cases[,1],
                  low_risk=py$cases[,2],
                  high_risk=py$cases[,3]) %>%
  pivot_longer(!age,names_to="scenario",values_to="count") %>%
  mutate(age_log = log(age),
         count_log = log(count)) %>%
  filter((age >= 30) & (age <= 80))

ggplot(sim,aes(x=age_log,y=count_log))+
  geom_point()+xlab("log(Age)")+ylab("log incidence")
ggsave("../plots/multistep_simulated_log.pdf",width=5,height=3)

ggplot(sim,aes(x=age,y=count))+
  geom_point()+xlab("Age")+ylab("Cases")
ggsave("../plots/multistep_simulated_cases.pdf",width=5,height=3)

```
